# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180421_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tagline_text',
            field=models.TextField(default='A Journey In Code, Chemistry, and Cheerleading'),
            preserve_default=False,
        ),
    ]
