# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_page_tagline_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('tagline', models.TextField()),
                ('content', models.TextField()),
                ('scroll_button', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='tagline_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_text',
        ),
        migrations.AddField(
            model_name='page',
            name='section_header',
            # error in default value set meant migration command was not completed
            # manually changed default value
            # need both default=None and null=True
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Section'),
            preserve_default=False,
        ),
    ]
