# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20180516_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='section_header',
        ),
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Section'),
            preserve_default=False,
        ),
    ]
