# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20180516_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='header',
        ),
        migrations.AddField(
            model_name='page',
            name='section_header',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
