# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20180516_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='section_header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Section'),
        ),
    ]
