# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20180516_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section_about_me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to='mysite.Section'),
        ),
        migrations.AlterField(
            model_name='page',
            name='section_header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='header', to='mysite.Section'),
        ),
    ]
