# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20180517_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='page', max_length=100),
            preserve_default=False,
        ),
    ]
