# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='scroll_button',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='tagline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
