# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20180521_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section_chemistry_projects',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='chemistry_projects', to='mysite.Section'),
        ),
    ]
