# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_page_section_chemistry_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section_cheerleading',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='cheerleading', to='mysite.Section'),
        ),
    ]
